### ISSUE TITLE
TVN_GETINFOTIPA

### ISSUE THREAD

**Issue by iPhilip** [AHK-just-me/AHK_Gui_Constants#1]
Hi just me,

https://github.com/AHK-just-me/AHK_Gui_Constants/blob/92bd0250a3bddbcb9f984dafd811631fd4e29606/Sources/Const_TreeView.ahk#L82

I believe that -412  should be -413.

**Comment by AHK-just-me** [comment]
Hi iPhilipp,
I fixed it.
Thanks!
