### ISSUE TITLE
Incorrect TVN_BEGINLABELEDITW value

### ISSUE THREAD

**Issue by iPhilip** [AHK-just-me/AHK_Gui_Constants#2]
Hi just me,

https://github.com/AHK-just-me/AHK_Gui_Constants/blob/92bd0250a3bddbcb9f984dafd811631fd4e29606/Sources/Const_TreeView.ahk#L73

I believe that -456 should be -459.

**Comment by AHK-just-me** [comment]
Thanks, I fixed it.

**Comment by iPhilip** [comment]
Not quite. You added a couple of comments but forgot to make the actual change.
